// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpAfI_-v21iI5frA6mdLa3XoUleFtoKcM',
    appId: '1:1071625977644:web:d09a3121c48da242933689',
    messagingSenderId: '1071625977644',
    projectId: 'myfirstprojectfirebase-e37b4',
    authDomain: 'myfirstprojectfirebase-e37b4.firebaseapp.com',
    storageBucket: 'myfirstprojectfirebase-e37b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkHEJoe2tutrso0Pt7XjcY8SzwKSWNEj0',
    appId: '1:1071625977644:android:f1af7de1db988e15933689',
    messagingSenderId: '1071625977644',
    projectId: 'myfirstprojectfirebase-e37b4',
    storageBucket: 'myfirstprojectfirebase-e37b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNBQ4gIRbyj7lk0m0xja-bq_nM2nqNrw',
    appId: '1:1071625977644:ios:54ee01ecbd61ef59933689',
    messagingSenderId: '1071625977644',
    projectId: 'myfirstprojectfirebase-e37b4',
    storageBucket: 'myfirstprojectfirebase-e37b4.firebasestorage.app',
    iosBundleId: 'com.example.birthday',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvNBQ4gIRbyj7lk0m0xja-bq_nM2nqNrw',
    appId: '1:1071625977644:ios:54ee01ecbd61ef59933689',
    messagingSenderId: '1071625977644',
    projectId: 'myfirstprojectfirebase-e37b4',
    storageBucket: 'myfirstprojectfirebase-e37b4.firebasestorage.app',
    iosBundleId: 'com.example.birthday',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpAfI_-v21iI5frA6mdLa3XoUleFtoKcM',
    appId: '1:1071625977644:web:81bb852beac5e522933689',
    messagingSenderId: '1071625977644',
    projectId: 'myfirstprojectfirebase-e37b4',
    authDomain: 'myfirstprojectfirebase-e37b4.firebaseapp.com',
    storageBucket: 'myfirstprojectfirebase-e37b4.firebasestorage.app',
  );
}